### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by lpc2000-begin** [HLT-NLP/PromptRank#5]
您好，运行代码没有结果，然而之前可以复现出论文结果。最近调整代码的过程中，却发现代码不报错也没有输出，即使采用原来没有修改的代码也是这个问题，请问您现在还可以正常运行这个代码吗

**Comment by lpc2000-begin** [comment]
目前发现的问题是一到这行代码就卡住了，导致后续进行不下去
StanfordCoreNLP_path = '/home/lipengcheng/NLP/stanford-corenlp-full-2018-02-27'

**Comment by lpc2000-begin** [comment]
目前发现的问题是一到这行代码就卡住了，导致后续进行不下去，路径是正确的

en_model = StanfordCoreNLP(StanfordCoreNLP_path, quiet=True)

**Comment by lpc2000-begin** [comment]
from stanfordcorenlp import StanfordCoreNLP
print(123)
#默认是英文
nlp = StanfordCoreNLP(r'D:\NLP代码\stanford-corenlp-full-2018-02-27')
print(123)
print(nlp.word_tokenize('This is an example of tokenziation.'))
#结果：['This', 'is', 'an', 'example', 'of', 'tokenziation', '.']
这段代码我在本地可以正常运行，服务器上面却运行不了

**Comment by lpc2000-begin** [comment]
INFO:root:Initializing native server...
INFO:root:java -Xmx4g -cp "/home/lipengcheng/NLP/stanford-corenlp-full-2018-02-27/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9022
INFO:root:Server shell PID: 275197
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
   275197
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
Exception in thread "main" java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at edu.stanford.nlp.io.IOUtils.writeStringToFile(IOUtils.java:167)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.<init>(StanfordCoreNLPServer.java:218)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1469)
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.
INFO:root:Waiting until the server is available.
我调试了之后发现是Exception in thread "main" java.io.IOException: No space left on device的问题，远程服务器根分区空间不足导致，于是调整使用的Stanford CoreNLP服务器临时目录为其他可用的分区空间位置，可惜改不了，后面看能不能清理根分区或者扩容。
